on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: '23.0.3'
          elixir-version: '1.10.4'
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --force --return-errors
